export const profile = {
  es_ES: {
    "profile.login.title": "Inicia sesión",
    "profile.login.labelUser": "Celular o correo electrónico",
    "profile.login.labelPassword": "Contraseña",
    "profile.login.labelRecover": "¿Olvidaste tu contraseña?",
    "profile.login.buttonlogIn": "Iniciar sesión",
    "profile.login.labelText": "¿Aún no tienes una cuenta?",
    "profile.login.buttonSignUp": "Regístrate",
    "profile.login.spanish": "Español",
    "profile.login.english": "Inglés",

    "profile.register.title": "Regístrate",
    "profile.register.labelName": "Nombre",
    "profile.register.labelPhone": "Número de celular",
    "profile.register.labelEmail": "Correo electrónico",
    "profile.register.labelPassword": "Contraseña",
    "profile.register.instructions": "Utiliza 8 caracteres o más: mayúsculas, minúsculas, números y caracteres especiales",
    "profile.register.buttonNext": "Siguiente",
    "profile.register.labelText": "Al hacer clic en “Siguiente” aceptas los",
    "profile.register.labelTextTerms": "Términos y condiciones",
    "profile.register.labelTextAnd": "y",
    "profile.register.labelTextPolicy": "Política de privacidad.",
    "profile.codeConfirmationModal.title": "Valida tu celular",
    "profile.codeConfirmationModal.subtitle": "Elige cómo validar tu número",
    "profile.codeConfirmationModal.fillLabel": "Enviar por WhatsApp",
    "profile.codeConfirmationModal.outlineLabel": "Enviar código por SMS",
    "profile.confirmationEmailModal.title": "¡Último paso!",
    "profile.confirmationEmailModal.subtitle": "Para finalizar validemos tu correo electrónico",
    "profile.confirmationEmailModal.fillLabel": "Continuar",
    "profile.codeConfirmation.titleReset": "Verifica tu correo",
    "profile.codeConfirmation.phone": "Valida tu celular",
    "profile.codeConfirmation.confirmPassword": "Las contraseñas no coinciden.",
    "profile.codeConfirmation.email": "Valida tu correo",
    "profile.codeConfirmation.subtitlePhone": "Hemos enviado un código de validación al celular ",
    "profile.codeConfirmation.subtitleEmail": "Hemos enviado un código de validación al correo ",
    "profile.codeConfirmation.subtitleReset": "Hemos enviado un código de confirmación al correo ",
    "profile.codeConfirmation.textCode": "¿No recibes el código?",
    "profile.codeConfirmation.resend": "Reenviar",
    "profile.confirmEmail.title": "Recuperar contraseña",
    "profile.confirmEmail.titleButton": "Siguiente",
    "profile.resetPassword.title": "Nueva contraseña",
    "profile.resetPassword.label1": "Nueva contraseña",
    "profile.resetPassword.label2": "Confirma tu nueva contraseña",
    "profile.resetPassword.newPasswordInstructions": "Utiliza 8 caracteres o más: mayúsculas, minúsculas, números y caracteres especiales",
    "profile.resetPassword.labelButton": "Volver para iniciar sesión",
    "profile.resetPassword.buttonTitle": "Siguiente",
    "profile.welcome": "Bienvenido",
    "profile.cards.title": "Tarjetas",
    "profile.cards.newCard": "Nueva tarjeta",
    "profile.addCard.advice": "😊 Por favor, confirma tu tarjeta para terminar tu comprar 💁",
    "profile.addCard.saveCard": "Guardar tarjeta",
    "profile.addCard.safetyLabel": "Tu tarjeta está 100% segura, solo guardaremos el número, volveremos a pedirte el código para confirmar tu compra.",
    "profile.addCard.buttonSave": "Guardar",
    "profile.home.orders": "Pedidos",
    "profile.home.orders.empty": "No tienes pedidos",
    "profile.home.orders.subtitle": "Aquí podrás gestionar todos tus pedidos",
    "profile.home.orders.seeMore": "Ver más",
    "profile.home.product": "producto",
    "profile.home.products": "productos",
    "profile.home.order": "Pedido",
    "profile.home.pendingPayment": "PENDIENTE DE PAGO",
    "profile.home.label.pendingPayment": "Pendiente de pago",
    "profile.home.sublabel.pendingPayment": "Prepararemos tu pedido una vez hayas hecho el pago",
    "profile.home.download.title": "Descarga", 
    "profile.home.download.subtitle": " la APP móvil",    
    "profile.home.download.button": "Descargar en",  
    "profile.home.coupons": "Cupones",
    "profile.home.favourite": "Favoritos",
    "profile.home.direction": "Direcciones",
    "profile.home.cards": "Tarjetas",
    "profile.home.billingInformation": "Datos de facturación",
    "profile.home.billingInformation.empty": "Aún no tienes ningun dato de facturación",
    "profile.home.billingInformation.empty.subtitle": "Agrega algun dato de facturación para comprar más rápido",
    "profile.home.help": "Ayuda",
    "profile.setting.title": "Configuración",
    "profile.setting.myAccount": "Mi cuenta",
    "profile.setting.personalInf": "Mis datos personales",
    "profile.setting.language": "Idioma",
    "profile.setting.screenMode": "Modo de pantalla",
    "profile.setting.about": "Acerca de",
    "profile.setting.logout": "Cerrar sesión",
    "profile.infPersonal.title": "Mis datos personales",
    "profile.infPersonal.photo": "Foto de perfil",
    "profile.infPersonal.name": "Nombre",
    "profile.infPersonal.email": "Correo electrónico",
    "profile.infPersonal.phone": "Celular",
    "profile.infPersonal.password": "Cambiar contraseña",
    "profile.infPersonal.modalEmail": "Ingresa tu correo electrónico",
    "profile.infPersonal.modalPhone": "Ingresa tu número de celular",
    "profile.modalPassw.title": "Cambiar contraseña",
    "profile.modalPassw.currentPass": "Contraseña actual",
    "profile.modalPassw.newPass": "Contraseña nueva",
    "profile.modalPassw.confirmPass": "Confirmar contraseña",
    "profile.modalPassw.save": "Guardar",
    "profile.validatePhone.title": "Valida tu número de celular",
    "profile.validatePhone.subtitle": "Hemos enviado un código de validación al celular",
    "profile.validatePhone.textCode": "¿No recibes el código?",
    "profile.validatePhone.resend": "Reenviar",
    "profile.validateEmail.title": "Valida tu correo electrónico",
    "profile.validateEmail.subtitle": "Hemos enviado un código de confirmación al correo",
    "profile.validateEmail.textCode": "¿No recibes el código?",
    "profile.validateEmail.resend": "Reenviar",
    "profile.modalLogout.title": "¿Quieres salir?",
    "profile.modalLogout.subtitle": "Puedes volver a ingresar cuando quieras",
    "profile.modalLogout.fillLabel": "Salir",
    "profile.modalLogout.outlineLabel": "Cancelar",
    "profile.language.title": "Idioma",
    "profile.language.spanish": "Español",
    "profile.language.english": "Ingles",
    "profile.changeMode.title": "Modo de pantalla",
    "profile.changeMode.automatic": "Automático",
    "profile.changeMode.light": "Claro",
    "profile.changeMode.dark": "Oscuro",
    "profile.about.title": "Acerca de",
    "profile.about.title.main": "Acerca de nosotros",
    "profile.about.about": "Sobre nosotros",
    "profile.about.exchanges": "Cambios y devoluciones",
    "profile.about.privacy": "Políticas de privacidad",
    "profile.about.terms": "Términos y condiciones",
    "profile.login.buttonLogin": "Iniciar sesión",
    "profile.orders.title": "Todos los pedidos",
    "profile.orders.favorites": "Favoritos",
    "profile.invoice.title": "Datos de facturación",
    "profile.invoice.newAccount": "Nueva cuenta",
    "profile.invoice.formTitle": "Crear datos de facturación",
    "profile.invoice.edit": "Editar",
    "profile.invoice.delete": "Eliminar",
    "profile.invoice.formName": "Nombre de la persona/compañia",
    "profile.invoice.formFiscalIdentifier": "Identificador fiscal",
    "profile.invoice.formFiscalAddress": "Dirección fiscal",
    "profile.invoice.formDefault": "Predeterminada",
    "profile.invoice.formSave": "Guardar",

    "profile.address.title": "Direcciones",
    "profile.address.select": "Seleccionar dirección",
    "profile.address.newAddress": "Nueva dirección",
    "profile.address.editAddress": "Editar dirección",
    "profile.address.empty.title": "No tienes ninguna dirección",
    "profile.address.empty.subtitle": "Agrega tu dirección para comprar más rápido",
    "profile.address.deleteAddress.title": "¿Eliminar dirección?",
    "profile.address.deleteAddress.subtitle": "¿Estás seguro que quieres eliminar esta dirección?",
    "profile.address.deleteAddress.succesfullyDeleted": "Dirección eliminada correctamente",
    "profile.address.formName": "Nombre",
    "profile.address.formAddress": "Dirección",
    "profile.address.formLabel": "Comienza agregando el nombre y dirección",
    "profile.address.formDefault": "Predeterminada",
    "profile.address.formPostalCode": "Código postal",

    "profile.help.title": "Ayuda",
    "profile.help.talkToSales": "Hablar con ventas",
    "profile.help.bookOfClaims": "Libro de reclamaciones",
    "profile.bookOfClaims.claimRegistered": "Reclamo registrado",
    "profile.bookOfClaims.claimSent": "Estimado usuario tu reclamo a sido registrado con éxito, hemos enviado una copia al correo que indicaste.",

    "profile.bookOfClaims.fullNames": "Nombre y apellidos",
    "profile.bookOfClaims.documentNumber": "Documento de identificación",
    "profile.bookOfClaims.docIdentification": "Doc. Identidad",
    "profile.bookOfClaims.docIdentification.passport": "Pasaporte",
    "profile.bookOfClaims.docIdentification.mmigrationCard": "Carnet de extranjería",
    "profile.bookOfClaims.docIdentification.dni": "Dni",
    "profile.bookOfClaims.email": "Correo",
    "profile.bookOfClaims.phone": "Celular",
    "profile.bookOfClaims.address": "Dirección",
    "profile.bookOfClaims.department": "Departamento",
    "profile.bookOfClaims.modalOptionSearch": "Buscar",
    "profile.bookOfClaims.departments": "Departamentos",
    "profile.bookOfClaims.province": "Provincia",
    "profile.bookOfClaims.provinces": "Provincias",
    "profile.bookOfClaims.district": "Distrito",
    "profile.bookOfClaims.districts": "Distritos",
    "profile.bookOfClaims.description": "Descripción de la incidencia",
    "profile.bookOfClaims.send": "Enviar",
    "profile.bookOfClaims.information": "Este formulario de reclamos es solo para usuarios de Perú, si eres de otro país escríbenos a este correo:",
    "profile.bookOfClaims.docNumber": "Numero de documento",


    "profile.cards.empty.title": "No tienes tarjetas",
    "profile.cards.empty.subtitle": "Agrega una tarjeta para comprar más rápido",

    "profile.cards.securityCode.title": "Cod. de seguridad",
    "profile.cards.securityCode.subtitle": "Código de 3 dígitos ubicados en el dorso de la tarjeta",

    "profile.cards.deleteCard.title": "Eliminar tarjeta",
    "profile.cards.deleteCard.subtitle": "¿Deseas eliminar esta tarjeta?",
    "profile.cards.deleteCard.outlineLabel": "Cancelar",
    "profile.cards.deleteCard.fillLabel": "Eliminar",
    "profile.cards.deleteCard.succesfullyDeleted": "Se eliminó la tarjeta correctamente",

    "profile.invoice.empty.title": "Aún no tienes datos de facturación",
    "profile.invoice.empty.subtitle": "Agrega una cuenta de facturación  para comprar más rápido",

    "profile.invoice.deleteInvoice.title": "¿Eliminar datos de facturación?",
    "profile.invoice.deleteInvoice.subtitle": "¿Estás seguro que quieres eliminar esta cuenta de facturación?",
    "profile.invoice.deleteInvoice.succesfullyDeleted": "Datos de facturación eliminado correctamente",

    "profile.modalCameraGallery.camera": "Cámara",
    "profile.modalCameraGallery.gallery": "Galería",

    "profile.orderStatusPopover.all": "Todos los pedidos",
    "profile.orderStatusPopover.inWay": "En camino",
    "profile.orderStatusPopover.preparation": "En preparación",
    "profile.orderStatusPopover.delivered": "Entregado",
    "profile.orderStatusPopover.cancelled": "Anulado",

    "profile.favorites.empty.title": "Aún no tienes favoritos",
    "profile.favorites.empty.subtitle": "Los productos que más te gustan aparecerán aquí",
    "profile.favorites.moveToBasketModal.title": "Mover a la cesta",
    "profile.favorites.moveToBasketModal.subtitle": "Una vez en tu cesta podrás comprar este producto",
    "profile.favorites.moveToBasketModal.move": "Mover",
    "profile.favorites.moveToBasket": "Mover a la cesta",
    "profile.favorites.succesfullyDeleted": "Se ha quitado de favoritos",
    "profile.favorites.succesfullyMovedToBasket": "Se agregó el producto al carrito de compras",

    "profile.coupons.title": "Mis cupones",
    "profile.coupons.empty": "No hay cupones",
    "profile.coupons.empty.subTitle": "No encontramos ningun cupon disponible",
    "profile.coupons.validate": "Validar",
    "profile.coupons.enterCode": "Ingresa el código",
    "profile.coupons.code": "CÓDIGO: ",
    "profile.coupons.conditions": "Condiciones",
    "profile.coupons.expires": "Vence: ",
    "profile.coupons.useCoupon": "Usar cupón",
    "profile.coupons.empty.title": "No tienes cupones",
    "profile.coupons.empty.subtitle": "No tienes cupones",
    "profile.optionsOrderPopover.edit": "Editar pedido",
    "profile.optionsOrderPopover.share": "Compartir",
    "profile.optionsOrderPopover.override": "Anular pedido",
    "profile.billingInfoPopover.text": "Aquí visualizarás tu comprobante de pago una vez hayas hecho el pago",
    "profile.orderDetail.titlePaymentMethod": "Método de pago",
    "profile.orderDetail.titleDelivery details": "Detalles de pedido",
    "profile.orderDetail.titleSummary": "Resumen de pedido",
    "profile.orderDetail.deposit": "Depósito o transferencia",
    "profile.orderDetail.instructions": "Ver instrucciones de pago",
    "profile.orderDetail.detailsDelivery": "Detalles de entrega",
    "profile.orderDetail.chargeAgency": "Agencia de carga",
    "profile.orderDetail.billingDetails": "Detalles de facturación",
    "profile.orderDetail.noDateFacturaction": "😊 No agregaste dato de facturación (te emitiremos una boleta simple)",
    "profile.orderDetail.homeDelivery": "Envío a domicilio",
    "profile.orderDetail.receiveOrder": "Recibirá el pedido",
    "profile.orderDetail.priceProducts": "Productos",
    "profile.orderDetail.costShopping": "Costo de envío",
    "profile.orderDetail.coupon": "Cupón",
    "profile.orderDetail.taxes": "Impuestos",
    "profile.orderDetail.delivered": "Entregado",
    "profile.orderDetail.delivered.information": "Tu pedido ya fue entregado en la dirección que indicaste",
    "profile.orderDetail.preparation": "En preparación",
    "profile.orderDetail.preparation.information": "Ya confirmamos tu pedido, se procederá a la preparaciòn",
    "profile.orderDetail.way": "En camino",
    "profile.orderDetail.way.information": "Tu pedido ya fue enviado a la dirección que indicaste",
    "profile.orderDetail.canceled": "Anulado",
    "profile.orderDetail.canceled.information": "Este pedido fue anulado",
    "profile.orderDetail.pickUp": "Recoge a partir del ",
    "profile.orderDetail.pickUpTime": " de 08:00am a 06:00pm",
    "profile.home.updatePersonalInformation": "Información del usuario actualizada de forma correcta.",
  },
  en_US: {
    "profile.login.title": "Log in",
    "profile.login.labelUser": "Phone or email",
    "profile.login.labelPassword": "Password",
    "profile.login.labelRecover": "Did you forget your password?",
    "profile.login.buttonlogIn": "Log in",
    "profile.login.labelText": "Do not you have an account yet?",
    "profile.login.buttonSignUp": "Sign up",
    "profile.login.spanish": "Spanish",
    "profile.login.english": "English",
    "profile.register.title": "Sign up",
    "profile.register.labelName": "Name",
    "profile.register.labelPhone": "Phone number",
    "profile.register.labelEmail": "Email address",
    "profile.register.labelPassword": "Password",
    "profile.register.instructions": "Use 8 or more characters: uppercase, lowercase, numbers, and special characters",
    "profile.register.buttonNext": "Next",
    "profile.register.labelText": "By clicking on “Next” you accept the",
    "profile.register.labelTextTerms": "Terms and Conditions",
    "profile.register.labelTextAnd": "and",
    "profile.register.labelTextPolicy": "Privacy Policy",
    "profile.codeConfirmationModal.title": "Validate your cell phone",
    "profile.codeConfirmationModal.subtitle": "Choose how to validate your number",
    "profile.codeConfirmationModal.fillLabel": "Send by WhatsApp",
    "profile.codeConfirmationModal.outlineLabel": "Send code by SMS",
    "profile.confirmationEmailModal.title": "Last step!",
    "profile.confirmationEmailModal.subtitle": "Finally we validate your email",
    "profile.confirmationEmailModal.fillLabel": "Continue",
    "profile.codeConfirmation.titleReset": "Check your email",
    "profile.codeConfirmation.subtitlePhone": "We have sent a validation code to the phone ",
    "profile.codeConfirmation.subtitleEmail": "We have sent a validation code to the email ",
    "profile.codeConfirmation.subtitleReset": "We have sent a confirmation code to the ",
    "profile.codeConfirmation.textCode": "Don't receive the code?",
    "profile.codeConfirmation.resend": "Resend",
    "profile.codeConfirmation.phone": "Validate your phone",
    "profile.codeConfirmation.confirmPassword": "Passwords do not match.",
    "profile.codeConfirmation.email": "Validate your email",
    "profile.confirmEmail.title": "Recover password",
    "profile.confirmEmail.titleButton": "Next",
    "profile.resetPassword.title": "New Password",
    "profile.resetPassword.label1": "New Password",
    "profile.resetPassword.label2": "Confirm your new password",
    "profile.resetPassword.newPasswordInstructions": "Use 8 or more characters: uppercase, lowercase, numbers, and special characters",
    "profile.resetPassword.labelButton": "Return to login",
    "profile.resetPassword.buttonTitle": "Next",
    "profile.welcome": "Welcome",
    "profile.cards.title": "Cards",
    "profile.cards.newCard": "New card",
    "profile.addCard.advice": "😊 Please confirm your card to finish your purchase 💁",
    "profile.addCard.saveCard": "Save card",
    "profile.addCard.safetyLabel": "Your card is 100% secure, we will only keep the number, we will ask you again for the code to confirm your purchase.",
    "profile.addCard.buttonSave": "Save",
    "profile.home.orders": "Orders",
    "profile.home.orders.empty": "You have no orders",
    "profile.home.orders.subtitle": "Here you can manage all your orders",
    "profile.home.orders.seeMore": "See more",
    "profile.home.order": "Order",
    "profile.home.pendingPayment": "Pending Payment",
    "profile.home.label.pendingPayment": "Pending payment",
    "profile.home.sublabel.pendingPayment": "We will prepare your order once you have made the payment",
    "profile.home.download.title": "Download", 
    "profile.home.download.subtitle": " the mobile APP",
    "profile.home.download.button": "Download in",  
    "profile.home.product": "product",
    "profile.home.products": "products",
    "profile.home.coupons": "Coupons",
    "profile.home.favourite": "Favorites",
    "profile.home.direction": "Address",
    "profile.home.cards": "Cards",
    "profile.home.billingInformation": "Billing information",
    "profile.home.billingInformation.empty": "You still do not have any billing information",
    "profile.home.billingInformation.empty.subtitle": "Add some billing information to purchase faster",
    "profile.home.help": "Help",
    "profile.setting.title": "Setting",
    "profile.setting.myAccount": "My account",
    "profile.setting.personalInf": "My personal information",
    "profile.setting.language": "Language",
    "profile.setting.screenMode": "Screen mode",
    "profile.setting.about": "About",
    "profile.setting.logout": "Sign off",
    "profile.infPersonal.title": "My personal information",
    "profile.infPersonal.photo": "Profile picture",
    "profile.infPersonal.name": "Name",
    "profile.infPersonal.email": "Email",
    "profile.infPersonal.phone": "Cell phone",
    "profile.infPersonal.password": "Change Password",
    "profile.infPersonal.modalEmail": "Enter your email",
    "profile.infPersonal.modalPhone": "Enter your phone",
    "profile.modalPassw.title": "Change Password",
    "profile.modalPassw.currentPass": "Current password",
    "profile.modalPassw.newPass": "New password",
    "profile.modalPassw.confirmPass": "Confirm Password",
    "profile.modalPassw.save": "Save",
    "profile.validatePhone.title": "Validate your cell phone number",
    "profile.validatePhone.subtitle": "We have sent a validation code to the cell phone",
    "profile.validatePhone.textCode": "Don't receive the code?",
    "profile.validatePhone.resend": "Resend",
    "profile.validateEmail.title": "Validate your email",
    "profile.validateEmail.subtitle": "We have sent a confirmation code to the email",
    "profile.validateEmail.textCode": "Don't receive the code?",
    "profile.validateEmail.resend": "Resend",
    "profile.modalLogout.title": "Do you want to hang out?",
    "profile.modalLogout.subtitle": "You can come back in whenever you want",
    "profile.modalLogout.fillLabel": "Exit",
    "profile.modalLogout.outlineLabel": "Cancel",
    "profile.about.title": "About",
    "profile.about.title.main": "About us",
    "profile.about.about": "About us",
    "profile.about.exchanges": "Returns & Exchanges",
    "profile.about.privacy": "Privacy policies",
    "profile.about.terms": "Terms and Conditions",
    "profile.changeMode.automatic": "Automatic",
    "profile.changeMode.dark": "Dark",
    "profile.changeMode.light": "Light",
    "profile.changeMode.title": "Screen Mode",
    "profile.language.english": "English",
    "profile.language.spanish": "Spanish",
    "profile.language.title": "Language",
    "profile.login.buttonLogin": "Log in",
    "profile.orders.title": "All orders",
    "profile.orders.favorites": "Favorites",
    "profile.invoice.title": "Billing data",
    "profile.invoice.newAccount": "New account",
    "profile.invoice.formTitle": "Create billing data",
    "profile.invoice.edit": "Edit",
    "profile.invoice.delete": "Delete",
    "profile.invoice.formName": "Name of the person/company",
    "profile.invoice.formFiscalIdentifier": "Fiscal Identifier",
    "profile.invoice.formFiscalAddress": "Fiscal Address",
    "profile.invoice.formDefault": "Default",
    "profile.invoice.formSave": "Save",

    "profile.address.title": "Addresses",
    "profile.address.select": "Select address",
    "profile.address.newAddress": "New address",
    "profile.address.editAddress": "Edit address",
    "profile.address.empty.title": "You have no addresses",
    "profile.address.empty.subtitle": "Add your address for faster checkout",
    "profile.address.deleteAddress.title": "Delete address?",
    "profile.address.deleteAddress.subtitle": "Are you sure you want to delete this address?",
    "profile.address.deleteAddress.succesfullyDeleted": "Address deleted successfully",
    "profile.address.formName": "Name",
    "profile.address.formAddress": "Address",
    "profile.address.formLabel": "Start by adding the name and address",
    "profile.address.formDefault": "Default",
    "profile.address.formPostalCode": "Postal code",

    "profile.help.title": "Help",
    "profile.help.talkToSales": "Talk to Sales",
    "profile.help.bookOfClaims": "Book of Claims",
    "profile.bookOfClaims.claimRegistered": "Registered claim",
    "profile.bookOfClaims.claimSent": "Dear user, your claim has been successfully registered, we have sent a copy to the email you indicated.",

    "profile.bookOfClaims.fullNames": "Name and surname",
    "profile.bookOfClaims.documentNumber": "Identification document",
    "profile.bookOfClaims.docIdentification": "Doc. Identity",
    "profile.bookOfClaims.docIdentification.passport": "Passport",
    "profile.bookOfClaims.docIdentification.mmigrationCard": "Immigration card",
    "profile.bookOfClaims.docIdentification.dni": "ID card",
    "profile.bookOfClaims.email": "Email",
    "profile.bookOfClaims.phone": "Phone",
    "profile.bookOfClaims.address": "Address",
    "profile.bookOfClaims.department": "Department",
    "profile.bookOfClaims.modalOptionSearch": "Search",
    "profile.bookOfClaims.departments": "Departments",
    "profile.bookOfClaims.province": "Province",
    "profile.bookOfClaims.provinces": "Provinces",
    "profile.bookOfClaims.district": "District",
    "profile.bookOfClaims.districts": "Districts",
    "profile.bookOfClaims.description": "Description of the incident",
    "profile.bookOfClaims.send": "Send",
    "profile.bookOfClaims.information": "This claim form is only for users from Peru, if you are from another country write to us at this email:",
    "profile.bookOfClaims.docNumber": "Document number",

    "profile.cards.empty.title": "You have no cards",
    "profile.cards.empty.subtitle": "Add a card for faster checkout",

    "profile.cards.securityCode.title": "Security Code",
    "profile.cards.securityCode.subtitle": "3-digit code located on the back of the card",

    "profile.cards.deleteCard.title": "Delete Card",
    "profile.cards.deleteCard.subtitle": "Do you want to delete this card?",
    "profile.cards.deleteCard.outlineLabel": "Cancel",
    "profile.cards.deleteCard.fillLabel": "Delete",
    "profile.cards.deleteCard.succesfullyDeleted": "Card was removed correctly",

    "profile.invoice.empty.title": "You do not have billing data yet",
    "profile.invoice.empty.subtitle": "Add a billing account for faster checkout",

    "profile.invoice.deleteInvoice.title": "Delete billing data?",
    "profile.invoice.deleteInvoice.subtitle": "Are you sure you want to delete this billing account?",
    "profile.invoice.deleteInvoice.succesfullyDeleted": "Billing data successfully deleted",

    "profile.modalCameraGallery.camera": "Camera",
    "profile.modalCameraGallery.gallery": "Gallery",

    "profile.orderStatusPopover.all": "All orders",
    "profile.orderStatusPopover.inWay": "On the way",
    "profile.orderStatusPopover.preparation": "In preparation",
    "profile.orderStatusPopover.delivered": "Delivered",
    "profile.orderStatusPopover.cancelled": "Cancelled",

    "profile.favorites.empty.title": "You don't have any favorites yet",
    "profile.favorites.empty.subtitle": "The products you like the most will appear here",
    "profile.favorites.moveToBasketModal.title": "Move to Basket",
    "profile.favorites.moveToBasketModal.subtitle": "Once in your basket, you can purchase this product",
    "profile.favorites.moveToBasketModal.move": "Move",
    "profile.favorites.moveToBasket": "Move to cart",
    "profile.favorites.succesfullyDeleted": "Removed from favorites",
    "profile.favorites.succesfullyMovedToBasket": "Product was added to the shopping cart",

    "profile.coupons.title": "My Coupons",
    "profile.coupons.empty": "There are no coupons",
    "profile.coupons.empty.subTitle": "We did not find any coupon available",
    "profile.coupons.validate": "Validate",
    "profile.coupons.enterCode": "Enter the code",
    "profile.coupons.conditions": "Conditions",
    "profile.coupons.expires": "Expires: ",
    "profile.coupons.code": "CODE: ",
    "profile.coupons.useCoupon": "Use Coupon",
    "profile.coupons.empty.title": "You have no coupons",
    "profile.coupons.empty.subtitle": "You have no coupons",
    "profile.optionsOrderPopover.edit": "Edit order",
    "profile.optionsOrderPopover.share": "Share",
    "profile.optionsOrderPopover.override": "Cancel order",
    "profile.billingInfoPopover.text": "Here you will see your payment receipt once you have made the payment",
    "profile.orderDetail.titlePaymentMethod": "Payment method",
    "profile.orderDetail.titleSummary": "Order summary",
    "profile.orderDetail.deposit": "Deposit or transfer",
    "profile.orderDetail.instructions": "View payment instructions",
    "profile.orderDetail.detailsDelivery": "Delivery details",
    "profile.orderDetail.chargeAgency": "Charge agency",
    "profile.orderDetail.billingDetails": "Billing details",
    "profile.orderDetail.noDateFacturaction": "😊 You did not add billing information (we will issue you a simple invoice)",
    "profile.orderDetail.homeDelivery": "Home delivery",
    "profile.orderDetail.receiveOrder": "You will receive the order",
    "profile.orderDetail.priceProducts": "Products",
    "profile.orderDetail.costShopping": "Cost of shipping",
    "profile.orderDetail.coupon": "Coupon",
    "profile.orderDetail.taxes": "Taxes",
    "profile.orderDetail.delivered": "Delivered",
    "profile.orderDetail.delivered.information": "Your order has already been delivered to the address you indicated",
    "profile.orderDetail.preparation": "In preparation",
    "profile.orderDetail.preparation.information": "We have already confirmed your order, the preparation will proceed",
    "profile.orderDetail.way": "On the way",
    "profile.orderDetail.way.information": "Your order has already been sent to the address you indicated",
    "profile.orderDetail.canceled": "Canceled",
    "profile.orderDetail.canceled.information": "This order was canceled",
    "profile.orderDetail.pickUp": "Pick up from ",
    "profile.orderDetail.pickUpTime": " from 08:00am to 06:00pm",
    
    "profile.home.updatePersonalInformation": "Correctly updated user information.",
  }
};
