export const basket = {
    es_ES: {
        "basket.welcome": "Bienvenido",
        "basket.home.title": "Mi cesta",
        "basket.home.empty.title": "Aún no agregas productos a tu cesta",
        "basket.home.empty.subtitle": "Empieza agregando tu primer producto",
        "basket.home.empty.goToPay": " Ir a pagar",

        "basket.storePickup.title": "Mi pedido",
        "basket.storePickup.detailsLabelTitle": "Detalles de entrega",
        "basket.storePickup.storeItemPlaceholder": "Elegir tienda",
        "basket.storePickup.addressItemPlaceholder": "Agregar dirección",
        "basket.storePickup.addressError": "Envío no disponibles a esta dirección",    
        "basket.storePickup.addresItArrives": "Llega en un periodo estimado de ",  
        "basket.storePickup.addresItArrivesDay": " días",  
        "basket.storePickup.addressRegularShipping": "Envío regular", 
        "basket.storePickup.addressAgency": "Entrega en ",
        "basket.storePickup.addressHowtoget": "Como llegar",    
        "basket.storePickup.dateDelivery": "Fecha de entrega",
        "basket.storePickup.typeOfShipmentItemPlaceholder": "Envío express",
        "basket.storePickup.authorizationItemPlaceholder": "¿Otra persona recogerá el pedido?",
        "basket.storePickup.authorizationItemPlaceholderSublabel": "Recogerá el pedido",
        "basket.storePickup.paymentLabelTitle": "Métodos de pago",
        "basket.storePickup.paymentItemPlaceholder": "Agregar método de pago",
        "basket.storePickup.requerimentsItemPlaceholder": "Requisitos para la entrega",
        "basket.storePickup.agencyOptionItemPlaceholder": "Elegir agencia",
        "basket.storePickup.summaryLabelTitle": "Resúmen de pedido",
        "basket.storePickup.billingLabelTitle": "Facturación ",
        "basket.storePickup.billingSpanTitle": "(Opcional)",
        "basket.storePickup.billingItemPlaceholder": "Agregar datos facturación",
        "basket.storePickup.couponsButton": "Agregar cupón",
        "basket.storePickup.priceBoxTitle": "Precio",
        "basket.storePickup.couponBoxTitle": "Cupón",
        "basket.storePickup.deliveryBoxTitle": "Costo de entrega",
        "basket.storePickup.totalBoxTitle": "Total",
        "basket.storePickup.buttonTotal": "Pagar ",
        "basket.storePickup.pickupInformationLabel1": "Te enviaremos un mensaje a tu correo y celular cuando tu pedido esté listo",
        "basket.storePickup.pickupInformationLabel2": "Una vez que tu pedido esté listo, tendrás 5 días para recogerlo",
        "basket.storePickup.pickupInformationLabel3": "Debes llevar tu DNI",
        "basket.storePickup.arrives": "Llega el",
        "basket.storePickup.seeTerms": "Ver términos y condiciones",
        "basket.storePickup.freightAgencies": "Agencias de carga",
        "basket.storePickup.stores": "Tiendas",
        "basket.storePickup.stores.empty": "No hay tiendas",
        "basket.storePickup.stores.empty.subTitle": "No encontramos ninguna tienda para esta dirección",

        "basket.deliveryDetailsPopover.labelHome": "Envío a domicilio",
        "basket.deliveryDetailsPopover.labelHome.empty": "No disponible para envío a domicilio",
        "basket.deliveryDetailsPopover.labelHome.empty.subTitle": "Seleccione otra dirección",
        "basket.deliveryDetailsPopover.labelAgency": "Agencia de carga",
        "basket.deliveryDetailsPopover.labelShop": "Recojo en tienda",

        "basket.orderReceiverModal.title": "¿Quién recibirá el pedido?",
        "basket.orderReceiverModal.itemName": "Nombre y apellidos",
        "basket.orderReceiverModal.itemIdentification": "Documento de identificación",
        "basket.orderReceiverModal.itemPosition": "Cargo o vínculo",
        "basket.orderReceiverModal.itemPhone": "Número de celular",
        "basket.orderReceiverModal.itemEmail": "Correo electrónico",
        "basket.orderReceiverModal.buttonConfirm": "Confirmar",
        "basket.orderReceiverModal.buttonCancel": "Cancelar",

        "basket.addCouponModal.title": "Agregar cupón",
        "basket.addCouponModal.placeholder": "Ingresa el código",
        "basket.addCouponModal.button": "Validar",
        "basket.addCouponModal.buttonUseCoupon": "Usar cupón",
        "basket.addCouponModal.buttonUselater": "Usar después",
        "basket.addCouponModal.buttonConditions": "Condiciones",
        "basket.addCouponModal.labelCode": "CÓDIGO:",
        "basket.addCouponModal.labelExpires": "Vence:",

        "basket.addBillingModal.title": "Datos de facturación",
        "basket.addBillingModal.buttonEdit": "Editar",
        "basket.addBillingModal.buttonAdd": "agregar datos de facturación",
        "basket.addBillingModal.buttonAdd.desktop": "Nueva Cuenta",
        "basket.addBillingModal.buttonConfirm": "Confirmar",
        "basket.addBillingModal.buttonCancel": "Cancelar",

        "basket.deliveryRequirements.title": "Requisitos para la entrega",
        "basket.deliveryRequirements.label": "Detalla consideraciones adicionales para la entrega de tu pedido (Opcional)",
        "basket.deliveryRequirements.buttonConfirm": "Confirmar",
        "basket.deliveryRequirements.buttonCancel": "Cancelar",

        "basket.myAddresses.title": "Mis direcciones",
        "basket.myAddresses.buttonEdit": "Editar",
        "basket.myAddresses.buttonAdd": "agregar dirección",
        "basket.myAddresses.buttonConfirm": "Confirmar",
        "basket.myAddresses.buttonCancel": "Cancelar",

        "basket.calendarModal.title": "¿Cuándo recibir?",
        "basket.calendarModal.button": "Confirmar",
        "basket.calendarModal.buttonCancel": "Cancelar",

        "basket.shippingOptions.titleStore": "Tienda",
        "basket.shippingOptions.titleChargeAgency": "Agencia de carga",
        "basket.shippingOptions.titleHomeDelivery": "Envío a domicilio",
        "basket.shippingOptions.labelCountry": "País",

        //Metodos de pago
        "basket.paymentMethods.title": "Métodos de pago",
        "basket.paymentMethods.newCard": "Nueva Tarjeta",
        "basket.paymentMethods.deposit": "Depósito o transferencia",
        "basket.paymentMethods.cashPay": "Pago efectivo",
        "basket.paymentMethods.buttomPayment": "Confirmar Pago",

        "basket.typeMethods.title": "Último paso",
        "basket.typeMethods.instructions": "Instrucciones",
        "basket.typeMethods.information": "1. Deposita o transfiere en una de nuestras cuentas bancarias.",
        "basket.typeMethods.information2": "2. Luego de realizar el abono envíanos la constancia a través del chat",
        "basket.typeMethods.information3": "aqui...",
        "basket.typeMethods.amount": "Importe: ",
        "basket.typeMethods.company": "Empresa:",
        "basket.typeMethods.textMessage": "😊 Por favor, confirma tus datos para terminar tu comprar 💁",
        "basket.typeMethods.textMessage2": "Tu tarjeta está 100% segura, solo guardaremos el número, volveremos a pedirte el código para confirmar tu compra.",
        "basket.typeMethods.textDNI": "Documento de identidad",
        "basket.typeMethods.textPhone": "Número de celular",
        "basket.typeMethods.buttonPayment": "Confirmar Pago",

        "basket.modalPayDecline.title": "Pago rechazado",
        "basket.modalPayDecline.subtitle": "Te recomendamos intentar con otra tarjeta o elegir otra forma de pago",
        "basket.modalPayDecline.buttom": "Intentar de nuevo",

        "basket.modalPayNot.title": "Ups, no se pudo realizar el pago",
        "basket.modalPayNot.subtitle": "Te recomendamos intentar con otra tarjeta o elegir otra forma de pago",
        "basket.modalPayNot.buttom": "Intentar de nuevo",

        "basket.successPay.title": "Pago exitoso",
        "basket.successPay.title.desktop": "Pedido exitoso",
        "basket.successPay.subtitle": "¡Gracias por su compra!",
        "basket.successPay.subtitle.desktop": "Gracias por su compra",
        "basket.successPay.buttom": "Ir a mis pedidos",
        "basket.successPay.buttom2": "Seguir comprando",

        "basket.voucher.codePay": "Tu código de pago",
        "basket.voucher.amountPay": "Importe a pagar S/12,896.00",
        "basket.voucher.textPay": "Tienes para pagar hasta el",
        "basket.voucher.textDate": "24 de agosto 2023",
        "basket.voucher.textBanks": "en cualquiera de los siguientes bancos:",
        "basket.voucher.textFollowNextSteps": "Sigue los siguientes pasos:",
        "basket.voucher.textStep1": "1. Ingresa a tu banco favorito, en la opción “Pago de servicios” elige la opción “Empresas”",
        "basket.voucher.textStep2": "2. Busca la empresa",
        "basket.voucher.textStep2.1": '"Geor Pagos"',
        "basket.voucher.textStep3": "3. Ingresa el código de pago",
        "basket.voucher.textCreditedInstantly": "Pagas y se acredita al instante",
        "basket.voucher.textShare": "Compartir",

        "basket.modal.deleteSubTitle": "¿Estás seguro que deseas quitar este producto de tu cesta?",
        "basket.modal.deleteTitle": "Eliminar producto",

        //FIN
    },
    en_US: {
        "basket.welcome": "Welcome",
        "basket.home.title": "My basket",
        "basket.home.empty.title": "You have not added products to your cart yet",
        "basket.home.empty.subtitle": "Start adding your first product",
        "basket.home.empty.goToPay": "Go to checkout",

        "basket.storePickup.title": "My order",
        "basket.storePickup.detailsLabelTitle": "Delivery details",
        "basket.storePickup.storeItemPlaceholder": "Choose store",
        "basket.storePickup.addressItemPlaceholder": "Add address",
        "basket.storePickup.addresItArrives": "It arrives in an estimated period of ", 
        "basket.storePickup.addresItArrivesDay": " days", 
        "basket.storePickup.addressRegularShipping": "Regular shipping",
        "basket.storePickup.addressAgency": "Delivery in ",  
        "basket.storePickup.addressHowtoget": "How to get",  
        "basket.storePickup.addressError": "Shipping not available to this address",
        "basket.storePickup.dateDelivery": "Date of delivery",
        "basket.storePickup.typeOfShipmentItemPlaceholder": "Express delivery",
        "basket.storePickup.authorizationItemPlaceholder": "Will someone else pick up the order?",
        "basket.storePickup.authorizationItemPlaceholderSublabel": "Will pick up the order",
        "basket.storePickup.paymentLabelTitle": "Payment methods",
        "basket.storePickup.paymentItemPlaceholder": "Add payment method",
        "basket.storePickup.requerimentsItemPlaceholder": "Requirements for delivery",
        "basket.storePickup.agencyOptionItemPlaceholder": "Choose agency",
        "basket.storePickup.summaryLabelTitle": "Order Summary",
        "basket.storePickup.billingLabelTitle": "Billing ",
        "basket.storePickup.billingSpanTitle": "(Optional)",
        "basket.storePickup.billingItemPlaceholder": "Add billing information",
        "basket.storePickup.couponsButton": "Add coupon",
        "basket.storePickup.priceBoxTitle": "Price",
        "basket.storePickup.couponBoxTitle": "Coupon",
        "basket.storePickup.deliveryBoxTitle": "Delivery cost",
        "basket.storePickup.totalBoxTitle": "Total",
        "basket.storePickup.buttonTotal": "Pay ",
        "basket.storePickup.pickupInformationLabel1": "We will send you a message to your email and cell phone when your order is ready",
        "basket.storePickup.pickupInformationLabel2": "Once your order is ready, you will have 5 days to pick it up",
        "basket.storePickup.pickupInformationLabel3": "You must bring your DNI",
        "basket.storePickup.arrives": "He arrives",
        "basket.storePickup.seeTerms": "See terms and conditions",
        "basket.storePickup.freightAgencies": "Freight agencies",
        "basket.storePickup.stores": "Stores",
        "basket.storePickup.stores.empty": "There are no stores",
        "basket.storePickup.stores.empty.subTitle": "We did not find any stores for this address.",

        "basket.deliveryDetailsPopover.labelHome": "Home delivery",
        "basket.deliveryDetailsPopover.labelHome.empty": "Not available for home delivery",
        "basket.deliveryDetailsPopover.labelHome.empty.subTitle": "Select another address",
        "basket.deliveryDetailsPopover.labelAgency": "Freight agency",
        "basket.deliveryDetailsPopover.labelShop": "Pick up in store",

        "basket.orderReceiverModal.title": "Who will receive the order?",
        "basket.orderReceiverModal.itemName": "Name and surname",
        "basket.orderReceiverModal.itemIdentification": "Identification document",
        "basket.orderReceiverModal.itemPosition": "Position or link",
        "basket.orderReceiverModal.itemPhone": "Cell phone number",
        "basket.orderReceiverModal.itemEmail": "Email",
        "basket.orderReceiverModal.buttonConfirm": "Confirm",
        "basket.orderReceiverModal.buttonCancel": "Cancel",

        "basket.addCouponModal.title": "Add coupon",
        "basket.addCouponModal.placeholder": "Enter the code",
        "basket.addCouponModal.button": "Validate",
        "basket.addCouponModal.buttonUseCoupon": "Use coupon",
        "basket.addCouponModal.buttonUselater": "Use later",
        "basket.addCouponModal.buttonConditions": "Conditions",
        "basket.addCouponModal.labelCode": "CODE:",
        "basket.addCouponModal.labelExpires": "Expires:",

        "basket.addBillingModal.title": "Billing details",
        "basket.addBillingModal.buttonEdit": "Edit",
        "basket.addBillingModal.buttonAdd": "add billing information",
        "basket.addBillingModal.buttonAdd.desktop": "new account",
        "basket.addBillingModal.buttonCancel": "Cancel",
        "basket.addBillingModal.buttonConfirm": "Confirm",

        "basket.deliveryRequirements.title": "Requirements for delivery",
        "basket.deliveryRequirements.label": "Detail additional considerations for the delivery of your order (Optional)",
        "basket.deliveryRequirements.buttonConfirm": "Confirm",
        "basket.deliveryRequirements.buttonCancel": "Cancel",

        "basket.myAddresses.title": "My Addresses",
        "basket.myAddresses.buttonAdd": "add address",

        "basket.calendarModal.title": "When to receive?",
        "basket.calendarModal.button": "Confirm",
        "basket.calendarModal.buttonCancel": "Cancel",

        "basket.shippingOptions.titleStore": "Store",
        "basket.shippingOptions.titleChargeAgency": "Charge agency",
        "basket.shippingOptions.titleHomeDelivery": "Home delivery",
        "basket.shippingOptions.labelCountry": "Country",

        //Metodos de pago
        "basket.paymentMethods.title": "Payment methods",
        "basket.paymentMethods.newCard": "New card",
        "basket.paymentMethods.deposit": "Deposit or transfer",
        "basket.paymentMethods.cashPay": "Cash payment",
        "basket.paymentMethods.buttomPayment": "Confirm payment",

        "basket.typeMethods.title": "Last step",
        "basket.typeMethods.instructions": "Instructions",
        "basket.typeMethods.information": "1. Deposit or transfer to one of our bank accounts.",
        "basket.typeMethods.information2": "2. After making the payment, send us the proof via chat",
        "basket.typeMethods.information3": "here...",
        "basket.typeMethods.amount": "Amount: ",
        "basket.typeMethods.company": "Company:",
        "basket.typeMethods.textMessage": "😊 Please confirm your information to complete your purchase 💁",
        "basket.typeMethods.textMessage2": "Your card is 100% secure, we will only save the number, we will ask you again for the code to confirm your purchase.",
        "basket.typeMethods.textDNI": "Identification document",
        "basket.typeMethods.textPhone": "Cell phone number",
        "basket.typeMethods.buttonPayment": "Confirm payment",

        "basket.modalPayDecline.title": "Payment declined",
        "basket.modalPayDecline.subtitle": "We recommend you try another card or choose another payment method",
        "basket.modalPayDecline.buttom": "Try again",

        "basket.modalPayNot.title": "Oops, payment could not be made",
        "basket.modalPayNot.subtitle": "We recommend you try another card or choose another payment method.",
        "basket.modalPayNot.buttom": "Try again",

        "basket.successPay.title": "Successful payment",
        "basket.successPay.title.desktop": "Successful order",
        "basket.successPay.subtitle": "Thanks for your purchase!",
        "basket.successPay.subtitle.desktop": "Thanks for your purchase!",
        "basket.successPay.buttom": "Go to My orders",
        "basket.successPay.buttom2": "Keep buying",

        "basket.voucher.codePay": "Your payment code",
        "basket.voucher.amountPay": "Amount to pay S/12,896.00",
        "basket.voucher.textPay": "You have to pay until",
        "basket.voucher.textDate": "August 24, 2023",
        "basket.voucher.textBanks": "at any of the following banks:",
        "basket.voucher.textFollowNextSteps": "Follow the next steps:",
        "basket.voucher.textStep1": "1. Enter your favorite bank, in the “Payment of services” option choose the “Companies” option",
        "basket.voucher.textStep2": "2. Search for the company",
        "basket.voucher.textStep2.1": '“Geor Payments”',
        "basket.voucher.textStep3": "3. Enter the payment code",
        "basket.voucher.textCreditedInstantly": "You pay and it is credited instantly",
        "basket.voucher.textShare": "Share",

        "basket.modal.deleteTitle": "Delete product",
        "basket.modal.deleteSubTitle": "Are you sure you want to remove this product from your basket?",



        //FIN
    }
}
