export const inbox = {
  es_ES: {
    "inbox.channel.me": "Yo",
    "inbox.channel.audio": "Audio",
    "inbox.channel.video": "Video",
    "inbox.channel.image": "Imagen",
    "inbox.dashboard.title": "Bandeja de entrada",
    "inbox.dashboard.write": "Escribe algo",
    "inbox.dashboard.file": "Agregar archivos",
    "inbox.dashboard.image": "Agregar imagenes",
    "inbox.dashboard.audio": "Agregar audios",
    "inbox.dashboard.video": "Agregar videos",
    "inbox.dashboard.login.title": "Iniciar sesión",
    "inbox.dashboard.login.subtitle": "Aquí podrás ver tus chats cuando hayas iniciado sesión o creado una cuenta",
    "inbox.dashboard.emoji.find": "Buscar...",
    "inbox.dashboard.emoji.search": "Buscar...",
    "inbox.dashboard.emoji.emojilist": "Elige un emoji...",
    "inbox.dashboard.emoji.notfound": "Sin resultados",
    "inbox.dashboard.emoji.clear": "Borrar",
    "inbox.dashboard.emoji.recent": "Recientes",
    "inbox.dashboard.emoji.people": "Emoticonos y personas",
    "inbox.dashboard.emoji.nature": "Animales y naturaleza",
    "inbox.dashboard.emoji.foods": "Comidas y bebidas",
    "inbox.dashboard.emoji.activity": "Actividades",
    "inbox.dashboard.emoji.places": "Viajes y destinos",
    "inbox.dashboard.emoji.objects": "Objetos",
    "inbox.dashboard.emoji.symbols": "Símbolos",
    "inbox.dashboard.emoji.flags": "Banderas",
    "inbox.dashboard.emoji.custom": "Personalizados",
    "inbox.dashboard.emoji.skin1": "Sin tono",
    "inbox.dashboard.emoji.skin2": "Claro",
    "inbox.dashboard.emoji.skin3": "Medio-Claro",
    "inbox.dashboard.emoji.skin4": "Medio",
    "inbox.dashboard.emoji.skin5": "Medio-Oscuro",
    "inbox.dashboard.emoji.skin6": "Oscuro"
  },
  en_US: {
    "inbox.channel.me": "You",
    "inbox.channel.audio": "Audio",
    "inbox.channel.video": "Video",
    "inbox.channel.image": "Image",
    "inbox.dashboard.title": "Inbox",
    "inbox.dashboard.write": "Type a message",
    "inbox.dashboard.file": "Add files",
    "inbox.dashboard.image": "Add images",
    "inbox.dashboard.audio": "Add audios",
    "inbox.dashboard.video": "Add videos",
    "inbox.dashboard.emoji.find": "Search...",
    "inbox.dashboard.emoji.search": "Search...",
    "inbox.dashboard.emoji.emojilist": "Pick an emoji...",
    "inbox.dashboard.emoji.notfound": "That emoji couldn't be found",
    "inbox.dashboard.emoji.clear": "Clear",
    "inbox.dashboard.emoji.recent": "Frequently used",
    "inbox.dashboard.emoji.people": "Smileys & People",
    "inbox.dashboard.emoji.nature": "Animals & Nature",
    "inbox.dashboard.emoji.foods": "Food & Drink",
    "inbox.dashboard.emoji.activity": "Activity",
    "inbox.dashboard.emoji.places": "Travel & Places",
    "inbox.dashboard.emoji.objects": "Objects",
    "inbox.dashboard.emoji.symbols": "Symbols",
    "inbox.dashboard.emoji.flags": "Flags",
    "inbox.dashboard.emoji.custom": "Custom",
    "inbox.dashboard.emoji.skin1": "Default",
    "inbox.dashboard.emoji.skin2": "Light",
    "inbox.dashboard.emoji.skin3": "Medium-Light",
    "inbox.dashboard.emoji.skin4": "Medium",
    "inbox.dashboard.emoji.skin5": "Medium-Dark",
    "inbox.dashboard.emoji.skin6": "Dark"
  }
}
