export const general = {
    es_ES: {
        "general.spanish": "Español",
        "general.english": "Ingles",
        "general.edit": "Editar",
        "general.delete": "Eliminar",
        "general.cancel": "Cancelar",
        "general.default": "Predeterminada",
        "general.confirm": "Confirmar",
        "general.card": "Tarjeta",
        "general.debit": "Débito",
        "general.credit": "Crédito",
        "general.unknown": "Desconocida",
        "general.insufficientStock": "No hay stock suficiente",
        "general.productAddedToCart": "Producto agregado a la cesta",
        "general.country": "País",
        "general.done": "Listo",
    },
    en_US: {
        "general.spanish": "Spanish",
        "general.english": "English",
        "general.edit": "Edit",
        "general.delete": "Delete",
        "general.cancel": "Cancel",
        "general.default": "Default",
        "general.confirm": "Confirm",
        "general.card": "Card",
        "general.debit": "Debit",
        "general.credit": "Credit",
        "general.unknown": "Unknown",
        "general.insufficientStock": "Not enough stock",
        "general.productAddedToCart": "Product added to cart",
        "general.country": "Country",
        "general.done": "Done",
    }
};